### ISSUE TITLE
not working in xcode 9.2

### ISSUE THREAD

**Issue by d33pak-s1ngh** [29satnam/InputAccessoryView#1]
This project is not opening in xcode 9.2 make it compatible to lower version. thank you

**Comment by 29satnam** [comment]
Hey, In the `General` try changing the`deployment target` to iOS 9
Let me know if this helps.
![screen shot 2018-05-29 at 11 51 28 am](https://user-images.githubusercontent.com/3638092/40641480-7172e98a-6337-11e8-843c-6749893bdb9f.png)

**Comment by d33pak-s1ngh** [comment]
it is not opening in xcode 9.2 so how would i will go in general ??

**Comment by 29satnam** [comment]
@d33pak-s1ngh mention some information bout error message for why it isn't opening.

**Comment by 29satnam** [comment]
I assume you got this figured out.
