### ISSUE TITLE
add media upload button at left of textfield

### ISSUE THREAD

**Issue by d33pak-s1ngh** [29satnam/InputAccessoryView#2]
thank you for this code can you add a media upload icon at very left of the textfield inside input view that will make it complete input accessory view for chatting.
till that i am trying to add it by my self.

**Comment by 29satnam** [comment]
@d33pak-s1ngh That's one nice suggestion, It will be added. Please `Star` this repo of you like it ;)

**Comment by 29satnam** [comment]
@d33pak-s1ngh Requested feature has been added.
![simulator screen shot - iphone x - 2018-05-30 at 00 20 56](https://user-images.githubusercontent.com/3638092/40678948-7ebeff76-639f-11e8-8257-3a0dddc5121d.png)
