### ISSUE TITLE
adding audio recording facility

### ISSUE THREAD

**Issue by d33pak-s1ngh** [29satnam/InputAccessoryView#3]
What about adding an icon for audio recording like whatsapp? which will disappear when user input text and can record audio on long press.

**Comment by 29satnam** [comment]
This is 3rd time you've been asking to add a feature, I remember ;)
I got two things to say. 
This project was built to fit my needs in a project, but is flexible enough to be reused by others wanting to build great messaging/comment app screens for iOS.
This isn't a pod where you'd find things difficult to patch up and add additional features.
About adding icons, all you need to know is the storyboarding and how you'd put the constraints together. Although the projects doesn't use a storyboard but the constraints runs the same way in the code as well.

**Comment by d33pak-s1ngh** [comment]
I have already implemented it. I was just telling so you can implement it
and make it more useful or ready for otheres.
