### ISSUE TITLE
Dragging down keyboard results in freeze 

### ISSUE THREAD

**Issue by ericsong01** [29satnam/InputAccessoryView#4]
There's a bug with the keyboard for iphoneXs that I'm also having with my project, where if you drag the keyboard down all the way down to the bottom, near the bottom, the screen will freeze. It results in a spike of CPU and memory usage begins to increase by 5 MB per seconds.

**Comment by 29satnam** [comment]
I will check it out.

**Comment by 29satnam** [comment]
https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode
This would be the solution.
